version: '3.8'

services:
  liga_front:
    container_name: liga_front
    build:
      context: .
      dockerfile: Dockerfile
      args:
          ENVIRONMENT: prod
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: production